import {AidModel} from "../../application/models/Aid.model";
import {AidEnv} from "../environment/Aid.env";

export const aid = {
    create: new AidModel(
        AidEnv.RID,
        AidEnv.TAV,
        AidEnv.LAV,
        AidEnv.PIX,
        AidEnv.TAC_DENIAL,
        AidEnv.TAC_ONLINE,
        AidEnv.TAC_DEFAULT,
        AidEnv.PRIORITY_INDEX,
        AidEnv.SELECTION_FLAGS,
        AidEnv.TERMINAL_CAPABILITIES_FOR_ALL_OPERATIONS,
        AidEnv.TERMINAL_CAPABILITIES_FOR_REFUND,
        AidEnv.TERMINAL_TRANSACTION_QUALIFIERS,
        AidEnv.TERMINAL_TRANSACTION_QUALIFIERS_FOR_REFUND,
        AidEnv.TRUSTED_PLATFORM_MODULE_CAPABILITIES,
        AidEnv.TRUSTED_PLATFORM_MODULE_CAPABILITIES_FOR_REFUND,
        AidEnv.ENHANCED_CONTACTLESS_READER_CAPABILITIES,
        AidEnv.ENHANCED_CONTACTLESS_READER_CAPABILITIES_FOR_REFUND,
        "",
        0,
        AidEnv.financialInstituteId,
    ),

    oddValues: new AidModel(
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.ODD_VALUES,
        AidEnv.id
    ),

    notSupportedLetters: new AidModel(
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.NOT_SUPPORTED_LETTERS,
        AidEnv.id
    ),

    bigValues: new AidModel(
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.BIG_VALUE,
        AidEnv.id
    ),

    edit: new AidModel(
        AidEnv.RID_UPDATE,
        AidEnv.TAV_UPDATE,
        AidEnv.LAV_UPDATE,
        AidEnv.PIX_UPDATE,
        AidEnv.TAC_DENIAL_UPDATE,
        AidEnv.TAC_ONLINE_UPDATE,
        AidEnv.TAC_DEFAULT_UPDATE,
        AidEnv.PRIORITY_INDEX_UPDATE,
        AidEnv.SELECTION_FLAGS_UPDATE,
        AidEnv.TERMINAL_CAPABILITIES_FOR_ALL_OPERATIONS_UPDATE,
        AidEnv.TERMINAL_CAPABILITIES_FOR_REFUND_UPDATE,
        AidEnv.TERMINAL_TRANSACTION_QUALIFIERS_UPDATE,
        AidEnv.TERMINAL_TRANSACTION_QUALIFIERS_FOR_REFUND_UPDATE,
        AidEnv.TRUSTED_PLATFORM_MODULE_CAPABILITIES_UPDATE,
        AidEnv.TRUSTED_PLATFORM_MODULE_CAPABILITIES_FOR_REFUND_UPDATE,
        AidEnv.ENHANCED_CONTACTLESS_READER_CAPABILITIES_UPDATE,
        AidEnv.ENHANCED_CONTACTLESS_READER_CAPABILITIES_FOR_REFUND_UPDATE
    )
};
